### ISSUE TITLE
somthing wrong occured when I run the job

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [Zuricho/ParallelFold#2]
hi,dear author , I installed the required modules according to the link requirements, but the following error occurred when I was running the script. Can you help me find out what is causing it? My installation steps are as follows:
1、conda create --prefix=/data/home/zhoujy/run/alphafold2 python=3.8
2、conda activate /data/home/zhoujy/run/alphafold2
3、conda install cudatoolkit=10.1 cudnn
4、pip install tensorflow==2.3.0
5、pip install biopython==1.79 chex==0.0.7 dm-haiku==0.0.4 dm-tree==0.1.6 immutabledict==2.0.0 jax==0.2.14 ml-collections==0.1.0
6、pip install --upgrade jax jaxlib==0.1.69+cuda101 -f https://storage.googleapis.com/jax-releases/jax_releases.html

and then , I run the script: 

#!/bin/bash
module load anaconda/2020.11
source activate /data/home/zhoujy/run/alphafold2
./run_feature.sh -d /data/public/alphafold2 -o /data/home/zhoujy/run/output -m model_1 -f /data/home/zhoujy/run/input/Tb927.10.2950.fasta -t 2021-07-27

result show as follows:
Traceback (most recent call last):
  File "/data/run01/zhoujy/ParallelFold-main/run_feature.py", line 33, in <module>
    from alphafold.model import data
  File "/data/run01/zhoujy/ParallelFold-main/alphafold/model/data.py", line 20, in <module>
    from alphafold.model import utils
  File "/data/run01/zhoujy/ParallelFold-main/alphafold/model/utils.py", line 21, in <module>
    import haiku as hk
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/haiku/__init__.py", line 17, in <module>
    from haiku import data_structures
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/haiku/data_structures.py", line 17, in <module>
    from haiku._src.data_structures import to_immutable_dict
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/haiku/_src/data_structures.py", line 30, in <module>
    from haiku._src import utils
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/haiku/_src/utils.py", line 24, in <module>
    import jax
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/__init__.py", line 16, in <module>
    from .api import (
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/api.py", line 38, in <module>
    from . import core
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/core.py", line 31, in <module>
    from . import dtypes
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/dtypes.py", line 31, in <module>
    from .lib import xla_client
  File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/lib/__init__.py", line 51, in <module>
    from jaxlib import pytree
ImportError: cannot import name 'pytree' from 'jaxlib' (/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jaxlib/__init__.py)

why ? I need you help

**Comment by Zuricho** [comment]
Recommend use this to find if there exist a cuda error.
```
python -c 'import tensorflow as tf; \
           print(tf.__version__);   \
           print(tf.test.is_gpu_available());'
```
Also, please check your cuda driver version by `nvidia-smi`

**Comment by zhoujingyu13687306871** [comment]
> 建议使用此来查找是否存在 cuda 错误。
> 
> ```
> python -c 'import tensorflow as tf; \
>            print(tf.__version__);   \
>            print(tf.test.is_gpu_available());'
> ```
> 
> 此外， 请检查您的 cuda 驱动程序版本由`nvidia-smi`

Thank you I get it
