### ISSUE TITLE
simtk.openmm.OpenMMException: Particle coordinate is nan

### ISSUE THREAD

**Issue by Kangfengyuuuu** [Zuricho/ParallelFold#47]
After generating MSA and features.pkl, I encountered the error simtk. openmm while running the structure prediction section OpenMMException: Particle coordinate is nan， The specific error is as follows: I0620 16:41:24.455497 140264108779328 run-alphafold. py: 243] Total JAX model model_1_multimer_v3_pred_4 on Os01t0149350-00Avr Pi9 predict time (including compilation time), see --benchmark): 90.7s
Traceback (most recent call last):
File "/home/kangfengyu/ParallelFold-main/run_alphafold.py",  line 491, in <module>
app.run(main)
File "/home/kangfengyu/miniconda3/envs/parafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
_run_main(main, args)
File "/home/kangfengyu/miniconda3/envs/parafold/lib/python3.8/site-packages/absl/app.py",  line 258, in _run_main
sys.exit(main(argv))
File "/home/kangfengyu/ParallelFold-main/run_alphafold.py", line 464, in main
predict_structure(
File "/home/kangfengyu/ParallelFold-main/run_alphafold.py",  line 299, in predict_structure
relaxed_pdb_str, _, violations = amber_relaxer.process(
File "/home/kangfengyu/ParallelFold-main/alphafold/relax/relax.py", line 62, in process
out = amber_minimize.run_pipeline(
File "/home/kangfengyu/ParallelFold-main/alphafold/relax/amber_minimize.py",  line 468, in run_pipeline
pdb_string = clean_protein(prot, checks=checks)
File "/home/kangfengyu/ParallelFold-main/alphafold/relax/amber_minimize.py",  line 173, in clean_protein
fixed_pdb = cleanup.fix_pdb(pdb_file, alterations_info)
File "/home/kangfengyu/ParallelFold-main/alphafold/relax/cleanup.py", line 55, in fix_pdb
fixer.addMissingAtoms(seed=0)
File "/home/kangfengyu/miniconda3/envs/parafold/lib/python3.8/site-packages/pdbfixer/pdbfixer.py",  line 954, in addMissingAtoms
mm.LocalEnergyMinimizer.minimize(context)
File "/home/kangfengyu/miniconda3/envs/parafold/lib/python3.8/site-packages/simtk/openmm/openmm.py",  line 4110, in minimize
return _openmm.LocalEnergyMinimizer_minimize(context,  tolerance, maxIterations)
simtk.openmm.OpenMMException: Particle coordinate is nan
My Python=3.8, cuda-nvcc =11.8.89，cudatoolkit=11.8.0，cudnn=8.9.1.23，openmm =7.5.1，tensorflow-gpu=2.9.0，jaxlib= 0.4.13+cuda11.cudnn86，jax=0.4.13
May I ask how to resolve this error? Is it a problem with the jax version? Is it still an issue with the Openmm version?

**Comment by istvan-tamas** [comment]
Hi,

Can You try to run it with **-t  2022-01-01**

If You run it with **-t 1800-01-01**  the model might not find templates, therefore there will be no coordinates.
With no coordinates, the relaxation step will fail, hence the OpenMM error.
